# Multiple Job Version of the Workflow
name: Generate ASCII Artwork

on: push 

jobs:
    build_job1:
        runs-on: ubuntu-latest
        steps:
            - name: Install Cowsay Program
              run: sudo apt-get install cowsay -y

            - name: Execute Cowsay CMD
              run: cowsay -f dragon "Run for cover, Im a DRAGON... GitHub Actions is awesome!" >> dragon.txt

            - name: Upload Dragon text File
              uses: actions/upload-artifact@v3
              with:
                  name: dragon-text-file
                  path: dragon.txt

    test_job2:
        needs: build_job1 # Ensure this "test_job2" job runs after build_job1
        runs-on: ubuntu-latest
        steps:
            - name: Download Dragon text File
              uses: actions/download-artifact@v3
              with:
                  name: dragon-text-file
                 # path: dragon.txt

            - name: Test File Exists
              run: grep -i "dragon" dragon.txt
           
    deploy_job3:
        needs: test_job2 #[test_job2,build_job1] # Ensure this "deploy_job3" job runs after test_job2 (and build_job1 if needed)ÃŸ
        runs-on: ubuntu-latest
        steps:
            - name: Download Dragon text File
              uses: actions/download-artifact@v3
              with:
                  name: dragon-text-file

            - name: Read File
              run: cat dragon.txt

            - name: Deploy
              run: echo "Deploying ASCII artwork..."
            
            # - name: install Cowsay Program # because of error: bash: cowsay: command not found (From first-example.yml workflow)
            #   run: sudo apt-get install cowsay -y

            # - name: Execute Cowsay CMD
            #   run: cowsay -f dragon "Run for cover, Im a DRAGON... GitHub Actions is awesome!" >> dragon.txt
            
            # - name: Test File Exists
            #   run: grep -i "dragon" dragon.txt

            # - name: Read File
            #   run: cat dragon.txt

            # - name: List Repository Files
            #   run: ls -ltra

# Single Job Version of the Above Workflow:
# name: Generate ASCII Artwork

# on: push 

# jobs:
#     build_job1:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Checkout Repository
#               uses: actions/checkout@v6

#             - name: List Repository Files
#               run: ls -ltra

#             - name: Executing Shell Script
#               run: |
#                     chmod +x ./ascii-script.sh
#                     ./ascii-script.sh