name: Generate ASCII Artwork

on: push 

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6
            
            - name: install Cowsay CMD # because of error: bash: cowsay: command not found (From first-example.yml workflow)
              run: sudo apt-get install cowsay -y

            - name: execute Cowsay CMD
              run: cowsay -f dragon "GitHub Actions is awesome!" >> dragon.txt
            
            - name: Test File Exists
              run: grep -i "dragon" dragon.txt

            - name: Read File
              run: cat dragon.txt

            - name: List Repository Files
              run: ls -ltra
